name: aguas_ecommerce
description: E-commerce para Agua de Lourdes

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_inappwebview: ^6.0.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  video_player: ^2.10.0
  google_maps_flutter: ^2.13.1
  google_maps_flutter_web: ^0.5.14+2
  image_picker: ^1.2.0
  path: ^1.9.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/